export const notificationsData = {
  transactionAlerts: [
    // CrossSwitch Dashboard Alerts (3 total)
    {
      id: 1,
      type: "warning",
      status: "flagged",
      title: "Suspicious Activity Detected",
      description:
        "Transaction CS001237 flagged for suspicious activity - R 450.75",
      timestamp: "2h ago",
      amount: "R 450.75",
      merchant: "Pharmacy Care",
      gateway: "CrossSwitch",
      transactionId: "CS001237",
      actionButton: "Investigate",
      actionRequired: true,
    },
    {
      id: 2,
      type: "warning",
      status: "unmatched",
      title: "Amount Discrepancy Detected",
      description: "Transaction CS001235 unmatched - R 875.50 discrepancy",
      timestamp: "4h ago",
      amount: "R 875.50",
      merchant: "FoodMart Express",
      gateway: "CrossSwitch",
      transactionId: "CS001235",
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 3,
      type: "error",
      status: "flagged",
      title: "Payment Method Mismatch",
      description:
        "Transaction CS001240 flagged - R 1,890.00 payment method issue",
      timestamp: "6h ago",
      amount: "R 1,890.00",
      merchant: "Electronics Hub",
      gateway: "CrossSwitch",
      transactionId: "CS001240",
      actionButton: "Investigate",
      actionRequired: true,
    },

    // Peach Payment Dashboard Alerts (5 total)
    {
      id: 4,
      type: "warning",
      status: "unmatched",
      title: "Amount Discrepancy Detected",
      description: "Transaction CS001235 unmatched - R 89.99 discrepancy",
      timestamp: "8h ago",
      amount: "R 89.99",
      merchant: "Coffee Corner",
      gateway: "PeachPayment",
      transactionId: "CS001235",
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 5,
      type: "error",
      status: "flagged",
      title: "Suspicious Activity Detected",
      description: "Transaction CS001237 flagged for review - R 125.50",
      timestamp: "12h ago",
      amount: "R 125.50",
      merchant: "Service Pro",
      gateway: "PeachPayment",
      transactionId: "CS001237",
      actionButton: "Investigate",
      actionRequired: true,
    },
    {
      id: 6,
      type: "warning",
      status: "unmatched",
      title: "Receipt Not Found",
      description: "Transaction CS001239 unmatched - R 75.25 receipt missing",
      timestamp: "16h ago",
      amount: "R 75.25",
      merchant: "Quick Mart",
      gateway: "PeachPayment",
      transactionId: "CS001239",
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 7,
      type: "error",
      status: "flagged",
      title: "Multiple Failed Attempts",
      description: "Transaction CS001242 flagged - R 899.99 multiple failures",
      timestamp: "20h ago",
      amount: "R 899.99",
      merchant: "Online Shop",
      gateway: "PeachPayment",
      transactionId: "CS001242",
      actionButton: "Investigate",
      actionRequired: true,
    },
    {
      id: 8,
      type: "warning",
      status: "unmatched",
      title: "Payment Verification Needed",
      description:
        "Transaction CS001245 unmatched - R 750.00 verification required",
      timestamp: "24h ago",
      amount: "R 750.00",
      merchant: "Gym Membership",
      gateway: "PeachPayment",
      transactionId: "CS001245",
      actionButton: "Review",
      actionRequired: true,
    },

    // Ozow Dashboard Alerts (5 total)
    {
      id: 9,
      type: "warning",
      status: "unmatched",
      title: "Amount Discrepancy Detected",
      description: "Transaction OZ001235 unmatched - R 79.99 discrepancy",
      timestamp: "1d ago",
      amount: "R 79.99",
      merchant: "Coffee Corner",
      gateway: "Ozow",
      transactionId: "OZ001235",
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 10,
      type: "error",
      status: "flagged",
      title: "Suspicious Activity Detected",
      description: "Transaction OZ001237 flagged for review - R 115.50",
      timestamp: "1d ago",
      amount: "R 115.50",
      merchant: "Service Pro",
      gateway: "Ozow",
      transactionId: "OZ001237",
      actionButton: "Investigate",
      actionRequired: true,
    },
    {
      id: 11,
      type: "warning",
      status: "unmatched",
      title: "Receipt Not Found",
      description: "Transaction OZ001239 unmatched - R 65.25 receipt missing",
      timestamp: "2d ago",
      amount: "R 65.25",
      merchant: "Quick Mart",
      gateway: "Ozow",
      transactionId: "OZ001239",
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 12,
      type: "error",
      status: "flagged",
      title: "Multiple Failed Attempts",
      description: "Transaction OZ001242 flagged - R 799.99 multiple failures",
      timestamp: "2d ago",
      amount: "R 799.99",
      merchant: "Online Shop",
      gateway: "Ozow",
      transactionId: "OZ001242",
      actionButton: "Investigate",
      actionRequired: true,
    },
    {
      id: 13,
      type: "warning",
      status: "unmatched",
      title: "Payment Verification Needed",
      description:
        "Transaction OZ001245 unmatched - R 650.00 verification required",
      timestamp: "3d ago",
      amount: "R 650.00",
      merchant: "Gym Membership",
      gateway: "Ozow",
      transactionId: "OZ001245",
      actionButton: "Review",
      actionRequired: true,
    },
  ],

  systemNotifications: [
    {
      id: 1,
      type: "warning",
      status: "pending",
      title: "CrossSwitch Reconciliation Alert",
      description: "3 flagged/unmatched transactions require attention",
      timestamp: "1h ago",
      alertCount: 3,
      totalTransactions: 15680,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 2,
      type: "warning",
      status: "pending",
      title: "Peach Payment Reconciliation Alert",
      description: "5 flagged/unmatched transactions require attention",
      timestamp: "12h ago",
      alertCount: 5,
      totalTransactions: 15420,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 3,
      type: "error",
      status: "failed",
      title: "Ozow Data Sync Error",
      description: "5 flagged/unmatched transactions require attention",
      timestamp: "16h ago",
      alertCount: 5,
      totalTransactions: 12850,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 4,
      type: "warning",
      status: "pending",
      title: "High Alert Rate Detected",
      description: "13 total alerts across all gateways require attention",
      timestamp: "24h ago",
      totalAlerts: 13,
      crossSwitchAlerts: 3,
      peachAlerts: 5,
      ozowAlerts: 5,
      actionButton: "Investigate",
      actionRequired: true,
    },
  ],

  reconciliationReports: [
    {
      id: 1,
      type: "warning",
      status: "pending",
      title: "CrossSwitch Reconciliation Required",
      description: "3 flagged/unmatched transactions need attention",
      timestamp: "3h ago",
      date: "2024-01-15",
      totalTransactions: 15680,
      alertCount: 3,
      matchedPercentage: 94.2,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 2,
      type: "warning",
      status: "pending",
      title: "Peach Payment Reconciliation Alert",
      description: "5 flagged/unmatched transactions require attention",
      timestamp: "8h ago",
      weekEnding: "2024-01-14",
      totalTransactions: 15420,
      alertCount: 5,
      matchedPercentage: 94.2,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 3,
      type: "warning",
      status: "pending",
      title: "Ozow Reconciliation Pending",
      description: "5 flagged/unmatched transactions need attention",
      timestamp: "24h ago",
      month: "January 2024",
      totalTransactions: 12850,
      alertCount: 5,
      matchedPercentage: 96.8,
      actionButton: "Review",
      actionRequired: true,
    },
    {
      id: 4,
      type: "error",
      status: "critical",
      title: "High Alert Rate Alert",
      description: "13 total alerts across all gateways",
      timestamp: "1d ago",
      totalAlerts: 13,
      crossSwitchAlerts: 3,
      peachAlerts: 5,
      ozowAlerts: 5,
      actionButton: "Investigate",
      actionRequired: true,
    },
  ],

  securityAlerts: [
    {
      id: 1,
      type: "error",
      status: "critical",
      title: "Suspicious Login Attempt",
      description: "Multiple failed login attempts detected from unknown IP",
      timestamp: "30m ago",
      ipAddress: "192.168.1.100",
      failedAttempts: 15,
      location: "Unknown",
      actionButton: "Investigate",
      actionRequired: true,
    },
  ],
};

export const getNotificationTypeData = (type) => {
  const typeMap = {
    transactionAlerts: notificationsData.transactionAlerts,
    systemNotifications: notificationsData.systemNotifications,
    reconciliationReports: notificationsData.reconciliationReports,
    securityAlerts: notificationsData.securityAlerts,
  };

  return typeMap[type] || [];
};

export const getNotificationTypeTitle = (type) => {
  const titleMap = {
    transactionAlerts: "Transaction Alerts",
    systemNotifications: "System Notifications",
    reconciliationReports: "Reconciliation Reports",
    securityAlerts: "Security & Pattern Alerts",
  };

  return titleMap[type] || "Notifications";
};

// Function to generate alerts based on actual transaction data
export const generateTransactionAlerts = (
  crossSwitchData,
  peachData,
  ozowData
) => {
  // Return the fixed alerts based on actual transaction data
  return notificationsData.transactionAlerts;
};

// Function to generate system notifications based on actual data
export const generateSystemNotifications = (
  crossSwitchData,
  peachData,
  ozowData
) => {
  // Return the fixed system notifications based on actual data
  return notificationsData.systemNotifications;
};
